# Generated by Django 5.2 on 2025-04-12 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=128)),
                ('business_name', models.CharField(blank=True, max_length=255)),
                ('receipt_number', models.CharField(blank=True, max_length=100)),
                ('total_price', models.CharField(blank=True, max_length=50)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('credit_card_last_4_digits', models.CharField(blank=True, max_length=10, null=True)),
                ('raw_ocr', models.JSONField()),
                ('structured_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
