# Generated by Django 5.2 on 2025-04-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='raw_ocr',
            new_name='items',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='structured_data',
        ),
        migrations.AlterField(
            model_name='receipt',
            name='business_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='credit_card_last_4_digits',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='payment_method',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='total_price',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='uid',
            field=models.CharField(max_length=255),
        ),
    ]
